# Generated by Django 5.0.3 on 2024-05-27 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anbieter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmenname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('telefonnummer', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('stadt', models.CharField(blank=True, max_length=100, null=True)),
                ('postleitzahl', models.CharField(blank=True, max_length=20, null=True)),
                ('land', models.CharField(blank=True, max_length=100, null=True)),
                ('oeffnungszeiten', models.JSONField(blank=True, default=dict, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='anbieter_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dienstleistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beschreibung', models.TextField()),
                ('dauer', models.DurationField()),
                ('additional_fields', models.JSONField(default=list)),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dienstleistungen', to='api.anbieter')),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startzeit', models.DateTimeField()),
                ('endzeit', models.DateTimeField()),
                ('additional_data', models.JSONField(default=list)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dienstleistung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dienstleistung')),
            ],
        ),
    ]
