# Generated by Django 5.0.3 on 2024-05-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anbieter_dienstleistung_buchung'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
