# Generated by Django 5.0.6 on 2024-06-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_provider_logo_provider_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='companyname',
            new_name='name',
        ),
    ]
